### ISSUE TITLE
Error on import after fresh install

### ISSUE THREAD

**Issue by ybayle** [nexusformat/python-nxs#11]
Hi,
I cannot import nxs after a fresh install. I get the following message:

Set NEXUSLIB or move NeXus to one of: C:\Users\bayle\Documents\PyNexusDji\python-nxs-master\nxs/libNeXus-0.dll, C:/Program Files/NeXus Data Format/bin/libNeXus-0.dll, C:\Users\bayle\Documents\PyNexusDji\python-nxs-master\nxs/libNeXus.dll

What should I do?
Thank you and have a nice day!

**Comment by mkoennecke** [comment]
Hi,


Am 16.03.2017 um 20:44 schrieb Yann Bayle <notifications@github.com<mailto:notifications@github.com>>:


Hi,
I cannot import nxs after a fresh install. I get the following message:

Set NEXUSLIB or move NeXus to one of: C:\Users\bayle\Documents\PyNexusDji\python-nxs-master\nxs/libNeXus-0.dll, C:/Program Files/NeXus Data Format/bin/libNeXus-0.dll, C:\Users\bayle\Documents\PyNexusDji\python-nxs-master\nxs/libNeXus.dll

What should I do?
Thank you and have a nice day!

It appears as if the NeXus shared library is not in the right place. Did you install it? It is one of the prerequisites for nxs.
It appears as if you are using windows, try finding the library in the windows search, search for libNeXus*.dll

If you cannot find it, install it. And if you have not done so, HDF5 too

If you can find it, copy it to one of the path where nxs tries to look for it or set the NEXUSLIB environment variable.

If you do not have to work with legacy NeXus files consider using h5py. Especially if you are reading only.


Best Regards,

  Mark Koennecke

**Comment by ybayle** [comment]
Ok, my bad, it is just a wrong path, I fixed it, thank you!
